#!/usr/bin/env python3
#
# smem - a tool for meaningful memory reporting
#
# Copyright 2008-2009 Matt Mackall <mpm@selenic.com>
#
# This software may be used and distributed according to the terms of
# the GNU General Public License version 2 or later, incorporated
# herein by reference.

from __future__ import print_function

import argparse
import csv
import errno
import functools
import json
import os
import pwd
import re
import sys
import tarfile
from io import TextIOWrapper
from multiprocessing import Pool, cpu_count
from typing import Dict, List, Optional, Sized, Union


class UIDCache(object):
    """Class for a simple ID Cache"""

    def __init__(self) -> None:
        self._cache = {}

    def __call__(self, uid):
        """Return if the entry is in cache, else populate the cache"""
        return self._cache.setdefault(uid, self._getpwuid(uid))

    @staticmethod
    def _getpwuid(uid: int) -> Union[int, str]:
        """Return the password database entry for the UID otherwise store just the UID"""
        try:
            return pwd.getpwuid(uid)[0]
        except KeyError:
            return str(uid)

class ProcReader(object):
    def __init(self) -> None:
        pass

    def listpids(self) -> List[str]:
        return []

    def piduser(self, pid):
        return -1

    def read(self, filename) -> str:
        """Return the file as a string"""
        return ""

    def username(self, uid):
        return "?" if uid == -1 else "%d" % uid

    def use_smaps_rollup(self):
        return False

    def allowed_cpu_count(self):
        return 1

class ProcFSReader(ProcReader):
    def __init__(self) -> None:
        self._uidcache = UIDCache()

    def listpids(self) -> List[str]:
        for e in os.listdir("/proc"):
            if e.isdigit():
                yield e

    def piduser(self, pid):
        """Return PID user data"""
        try:
            return os.stat("/proc/%d" % pid).st_uid
        except:
            return -1

    def read(self, filename) -> str:
        """Return the file as a string"""
        return open("/proc/" + filename).read()

    def username(self, uid):
        """Return username from UID cache"""
        return "?" if uid == -1 else self._uidcache(uid)

    def use_smaps_rollup(self):
        return os.access("/proc/%s/smaps_rollup" % os.getpid(), os.R_OK)

    def allowed_cpu_count(self):
        return cpu_count()

class TarfileReader(ProcReader):
    def __init__(self, filename) -> None:
        self._filename = filename
        self._tar = tarfile.open(filename)

    def listpids(self) -> List[str]:
        for tarinfo in self._tar:
            if tarinfo.name.endswith('/smaps'):
                yield tarinfo.name.split('/')[-2]

    def piduser(self, pid):
        try:
            return self._tar.getmember("%d" % pid).uid
        except KeyError:
            return -1

    def read(self, filename) -> str:
        """Return the file as a string"""
        try:
            f = self._tar.extractfile(filename)
            return TextIOWrapper(f).read() if f is not None else ''
        except KeyError:
            return ''

class Proc(object):
    """Helper class to handle /proc/ filesystem data"""

    def __init__(self) -> None:
        self._reader = options.source and TarfileReader(options.source) or ProcFSReader()
        pass

    def listpids(self) -> List[str]:
        return self._reader.listpids()

    def read(self, filename) -> str:
        """Return the file as a string"""
        return self._reader.read(filename)

    def readlines(self, filename):
        """Return the file as an list of lines"""
        return self.read(filename).splitlines(True)

    def piduser(self, pid):
        return self._reader.piduser(pid)

    def username(self, uid):
        return self._reader.username(uid)

    def version(self):
        """Return Linux version data"""
        return self.readlines("version")[0]

    def use_smaps_rollup(self):
        return self._reader.use_smaps_rollup()

    def allowed_cpu_count(self):
        return self._reader.allowed_cpu_count()

class MemData(Proc):
    """Class accessing and storing /proc/meminfo data"""

    def __init__(self) -> None:
        super().__init__()
        self._memdata = {}

        regex = re.compile("(?P<name>\\S+):\\s+(?P<amount>\\d+) kB")
        for line in self.readlines("meminfo"):
            match = regex.match(line)
            if match:
                self._memdata[match.group("name").lower()] = int(match.group("amount"))

    def __call__(self, entry):
        """Return the entry when the object is called"""
        return self._memdata[entry]


class ProcessData(Proc):
    """Helper class to handle /proc/<pid> filesystem data"""

    def __init__(self) -> None:
        super().__init__()

    def _iskernel(self, pid):
        """Check if it's a kernel pid"""
        return self.pidcmd(pid) == ""

    def pids(self) -> List[int]:
        """Get a list of PID's"""
        return [
            int(e)
            for e in self.listpids()
            if not self._iskernel(e)
            and ((options.pid and options.pid == int(e)) or not options.pid)
        ]

    def mapdata(self, pid):
        """Return PID smaps data"""
        return self.readlines("%s/smaps" % pid)

    def pidcmd(self, pid):
        """Return PID cmdline data"""
        try:
            c = self.read("%s/cmdline" % pid)[:-1]
            return c.replace("\0", " ")
        except:
            return "?"

    def pidusername(self, pid):
        """Return PID username"""
        return self.username(self.piduser(pid))


def totalmem():
    if options.realmem:
        return fromunits(options.realmem) / 1024
    else:
        memdata = MemData()
        return memdata("memtotal")


def pidmaps_with_pid(pid) -> (int, Dict[int, Dict[str,int]]):
    return pid, pidmaps(pid)

def pidmaps(pid) -> Dict[int, Dict[str, int]]:
    maps = {}
    start = None
    seen = False
    empty = True
    warned = False
    try:
        mapdata = proc.mapdata(pid)
    except:
        return {}

    for l in mapdata:
        empty = False
        f = l.split()
        if f[-1] == "kB":
            if f[0].startswith("Pss"):
                seen = True
            maps[start][f[0][:-1].lower()] = int(f[1])
        elif "-" in f[0] and ":" not in f[0]:  # looks like a mapping range
            start, end = f[0].split("-")
            start = int(start, 16)
            name = "<anonymous>"
            if len(f) > 5:
                name = f[5]
            maps[start] = dict(
                end=int(end, 16),
                mode=f[1],
                offset=int(f[2], 16),
                device=f[3],
                inode=f[4],
                name=name,
            )

    if not empty and not seen and not warned:
        print("Warning: Kernel does not appear to support PSS measurement")
        warned = True
        if not options.sort:
            options.sort = "rss"

    if options.mapfilter:
        f = {}
        for m in maps:
            if not filters(options.mapfilter, m, lambda x: maps[x]["name"]):
                f[m] = maps[m]
        return f
    return maps

def aggregate_name(name, mode=""):
    if name.startswith("[") or name.startswith("<"):
        return name
    elif name.startswith("anon_inode"):
        return name
    elif name.startswith("/usr/lib") or name.startswith("/lib"):
        return "[system libraries]"
    elif name.startswith("/dev/shm"):
        return "[shm]"
    elif (name.startswith("/dev/dri") or name.startswith("/dev/mali") or
          name.startswith("/dev/pvr") or name.startswith("/dev/kgsl") or
          "udmabuf" in name):
        return "[gpu devices]"
    elif name.startswith("/dev"):
        return "[other devices]"
    elif name.startswith("/usr/share/fonts") or name.startswith("/var/cache/fontconfig"):
        return "[fonts]"
    elif name.startswith("/memfd:") and "x" in mode:
        return "[jit code]"
    elif name.startswith("/memfd:"):
        return "[memfd]"
    elif name.endswith(".so") or re.search(r"\.so\.\d", name):
        return "[other libraries]"
    elif name.endswith(".pak") or name.endswith(".dat") or name.endswith(".bin"):
        return "[resources]"
    elif "x" in mode:
        return "[executables]"
    return "[other mappings]"

def maptotals(pids, allowed_cpu_count, is_aggregate=False):
    filtered_pids = filter(lambda pid: not filters(options.processfilter, pid, proc.pidcmd) and
                                       not filters(options.userfilter, pid, proc.pidusername),
                           pids)

    totals = {}
    pids_lists = {}
    with Pool(processes=allowed_cpu_count) as pool:
        for pid, maps in pool.map(pidmaps_with_pid, filtered_pids):
            if len(maps) == 0:
                continue
            seen = {}
            for m in list(maps.keys()):
                name = maps[m]["name"]
                if is_aggregate:
                    name = aggregate_name(name, maps[m].get("mode", ""))
                if name not in totals:
                    t = dict(
                        size=0,
                        rss=0,
                        pss=0,
                        shared_clean=0,
                        shared_dirty=0,
                        private_clean=0,
                        count=0,
                        private_dirty=0,
                        referenced=0,
                        swap=0,
                        pids=0,
                    )
                else:
                    t = totals[name]

                for k in t:
                    t[k] += maps[m].get(k, 0)
                t["count"] += 1
                if name not in seen:
                    t["pids"] += 1
                    seen[name] = 1
                    pids_lists.setdefault(name, []).append(str(pid))
                totals[name] = t
    for name in list(totals.keys()):
        totals[name]["pids_list"] = ",".join(pids_lists[name])


    return totals


def pidmaps_rollup(pid) -> Dict[int, Dict[str, int]]:
    try:
        smaps_rollup_lines = open("/proc/%s/smaps_rollup" % pid).read().splitlines(True)
    except:
        return {}
    header = smaps_rollup_lines[0]
    stats = smaps_rollup_lines[1:]
    maps = {}

    header_parts = header.split()
    start, end = header_parts[0].split("-")
    start = int(start, 16)
    name = header_parts[5] if len(header_parts) > 5 else "<rollup>"
    maps[start] = dict(
        end=int(end, 16),
        mode=header_parts[1],
        offset=int(header_parts[2], 16),
        device=header_parts[3],
        inode=header_parts[4],
        name=name,
    )

    for stat in stats:
        key = stat[0:16].rstrip(': ')
        value = stat[17:-3].strip()
        maps[start][key.lower()] = int(value)

    return maps


def pidtotals(pid, pidmaps_f=pidmaps) -> Dict[str, int]:
    maps = pidmaps_f(pid)
    if len(maps) == 0:
        return dict(pid=pid, maps=0)

    t = dict(
        pid=pid,
        size=0,
        rss=0,
        pss=0,
        shared_clean=0,
        shared_dirty=0,
        private_clean=0,
        private_dirty=0,
        referenced=0,
        swap=0,
    )
    for m in list(maps.keys()):
        for k in t:
            t[k] += maps[m].get(k, 0)

    t["uss"] = t["private_clean"] + t["private_dirty"]
    t["maps"] = len(maps)

    return t


def usertotals(pids, allowed_cpu_count, pidmaps_f=pidmaps):
    filtered_pids = list(filter(lambda p: not filters(options.processfilter, p, proc.pidcmd) and
                                          not filters(options.userfilter, p, proc.pidusername),
                                pids))

    totals = {}
    with Pool(processes=allowed_cpu_count) as pool:
        all_maps = pool.map(pidmaps_f, filtered_pids)
        for i in range(len(all_maps)):
            maps = all_maps[i]
            pid = filtered_pids[i]
            if len(maps) == 0:
                continue
            user = proc.piduser(pid)

            if user not in totals:
                t = dict(
                    size=0,
                    rss=0,
                    pss=0,
                    shared_clean=0,
                    shared_dirty=0,
                    private_clean=0,
                    count=0,
                    private_dirty=0,
                    referenced=0,
                    swap=0,
                )
            else:
                t = totals[user]

            for m in list(maps.keys()):
                for k in t:
                    t[k] += maps[m].get(k, 0)

            t["count"] += 1
            totals[user] = t

    return totals


def sortmaps(totals, key):
    l = []
    for pid in totals:
        l.append((totals[pid][key], pid))
    l.sort()
    return [pid for pid, key in l]


def units(x) -> str:
    s = ""
    if x == 0:
        return "0"
    for s in ("", "K", "M", "G", "T"):
        if x < 1024:
            break
        x /= 1024.0
    return "%.1f%s" % (x, s)


def fromunits(x) -> Optional[int]:
    s = dict(
        k=2**10,
        K=2**10,
        kB=2**10,
        KB=2**10,
        M=2**20,
        MB=2**20,
        G=2**30,
        GB=2**30,
        T=2**40,
        TB=2**40,
    )
    for k, v in list(s.items()):
        if x.endswith(k):
            return int(float(x[: -len(k)]) * v)
    sys.stderr.write("Memory size should be written with units, for example 1024M\n")
    sys.exit(-1)


def showamount(a, total: float):
    if options.abbreviate:
        return units(a * 1024)
    elif options.percent:
        if total == 0:
            return "N/A"
        return "%.2f%%" % (100.0 * a / total)
    return a


def filters(opt, arg, *sources) -> bool:
    if not opt:
        return False

    for f in sources:
        if re.search(opt, f(arg)):
            return False
    return True


def processtotals(pids, allowed_cpu_count, pidmaps_f=pidmaps):
    filtered_pids = filter(lambda pid: not filters(options.processfilter, pid, proc.pidcmd) and
                                       not filters(options.userfilter, pid, proc.pidusername),
                           pids)
    totals = {}
    with Pool(processes=allowed_cpu_count) as pool:
        for p in pool.map(functools.partial(pidtotals, pidmaps_f=pidmaps_f), filtered_pids):
            if p["maps"] != 0:
                totals[p["pid"]] = p

    return totals


def widthstr(field, width, default) -> str:
    if width == 0:
        return "%s"
    if width < 0:
        size = default
    else:
        size = width
        ignore_autosize.add(field)
    return "%-{size}.{size}s".format(size=size)


def chromium_role(cmd, chromium_binaries):
    """Return (role_label, group_key) for a Chromium process, or (None, None)."""
    if not cmd:
        return None, None
    binary = cmd.split()[0]
    name = os.path.basename(binary)
    m = re.search(r'--type=(\S+)', cmd)
    if m:
        type_val = m.group(1)
        if type_val == 'renderer':
            am = re.search(r'--app-id=(\S+)', cmd)
            detail = am.group(1) if am else ''
            label = ('%s [renderer] %s' % (name, detail)).rstrip()
            return label, '%s\x00renderer\x00%s' % (name, detail)
        if type_val == 'utility':
            sm = re.search(r'--utility-sub-type=(\S+)', cmd)
            detail = sm.group(1) if sm else ''
            label = ('%s [utility] %s' % (name, detail)).rstrip()
            return label, '%s\x00utility\x00%s' % (name, detail)
        label = '%s [%s]' % (name, type_val)
        return label, '%s\x00%s' % (name, type_val)
    if binary in chromium_binaries:
        return '%s [browser]' % name, '%s\x00browser' % name
    return None, None


def _group_by_chromium_role(pt, cmdlines):
    """Group process totals by Chromium role. Returns {group_key: {...}}."""
    chromium_binaries = {
        cmdlines[pid].split()[0]
        for pid in pt
        if re.search(r'--type=', cmdlines.get(pid, ''))
    }
    groups = {}
    for pid in pt:
        label, key = chromium_role(cmdlines.get(pid, ''), chromium_binaries)
        if key is None:
            continue
        if key not in groups:
            groups[key] = dict(label=label, pss=0, uss=0, rss=0, swap=0, count=0)
        g = groups[key]
        g['pss']   += pt[pid]['pss']
        g['uss']   += pt[pid]['uss']
        g['rss']   += pt[pid]['rss']
        g['swap']  += pt[pid]['swap']
        g['count'] += 1
    return groups


def _mem_thresholds():
    """Return (min_pss_kb, min_rss_kb) from options, 0 if not set."""
    pss = fromunits(options.min_pss) // 1024 if options.min_pss else 0
    rss = fromunits(options.min_rss) // 1024 if options.min_rss else 0
    return pss, rss


def showchromium(pidmaps_f=pidmaps) -> None:
    p = proc.pids()
    pt = processtotals(p, proc.allowed_cpu_count(), pidmaps_f)
    cmdlines = {pid: proc.pidcmd(pid) for pid in pt}
    groups = _group_by_chromium_role(pt, cmdlines)
    pss_min, rss_min = _mem_thresholds()
    if pss_min or rss_min:
        groups = {k: g for k, g in groups.items()
                  if g['pss'] >= pss_min and g['rss'] >= rss_min}

    fields = dict(
        role=(
            "Role",
            lambda k: groups[k]['label'],
            widthstr("role", options.role_width, 44),
            None,
            "Chromium process role",
        ),
        count=("Count", lambda k: groups[k]['count'], "% 5s", sum, "number of processes"),
        swap=("Swap",  lambda k: groups[k]['swap'],  "% 8a", sum, "swap consumed"),
        uss=("USS",   lambda k: groups[k]['uss'],   "% 8a", sum, "unique set size"),
        rss=("RSS",   lambda k: groups[k]['rss'],   "% 8a", sum, "resident set size"),
        pss=("PSS",   lambda k: groups[k]['pss'],   "% 8a", sum, "proportional set size"),
    )
    columns = options.columns or "role count pss uss rss"
    showtable(list(groups.keys()), fields, columns.split(), options.sort or "pss")


def showpids(pidmaps_f=pidmaps) -> None:
    p = proc.pids()
    pt = processtotals(p, proc.allowed_cpu_count(), pidmaps_f)
    pss_min, rss_min = _mem_thresholds()
    if pss_min or rss_min:
        pt = {k: v for k, v in pt.items()
              if v['pss'] >= pss_min and v['rss'] >= rss_min}

    def showuser(p):
        if options.numeric:
            return proc.piduser(p)
        return proc.pidusername(p)

    fields = dict(
        pid=("PID", lambda n: n, "% 6s", lambda x: len(pt), "process ID"),
        user=(
            "User",
            showuser,
            widthstr("user", options.user_width, 8),
            lambda x: len(dict.fromkeys(x)),
            "owner of process",
        ),
        command=(
            "Command",
            proc.pidcmd,
            widthstr("command", options.cmd_width, 27),
            None,
            "process command line",
        ),
        maps=("Maps", lambda n: pt[n]["maps"], "% 5s", sum, "total number of mappings"),
        swap=(
            "Swap",
            lambda n: pt[n]["swap"],
            "% 8a",
            sum,
            "amount of swap space consumed (ignoring sharing)",
        ),
        uss=("USS", lambda n: pt[n]["uss"], "% 8a", sum, "unique set size"),
        rss=(
            "RSS",
            lambda n: pt[n]["rss"],
            "% 8a",
            sum,
            "resident set size (ignoring sharing)",
        ),
        pss=(
            "PSS",
            lambda n: pt[n]["pss"],
            "% 8a",
            sum,
            "proportional set size (including sharing)",
        ),
        vss=(
            "VSS",
            lambda n: pt[n]["size"],
            "% 8a",
            sum,
            "virtual set size (total virtual memory mapped)",
        ),
    )
    columns = options.columns or "pid user command swap uss pss rss"

    showtable(list(pt.keys()), fields, columns.split(), options.sort or "pss")


def showmaps(is_aggregate=False) -> None:
    p = proc.pids()
    pt = maptotals(p, proc.allowed_cpu_count(), is_aggregate)
    pss_min, rss_min = _mem_thresholds()
    if pss_min or rss_min:
        pt = {k: v for k, v in pt.items()
              if v['pss'] >= pss_min and v['rss'] >= rss_min}

    fields = dict(
        map=(
            "Map",
            lambda n: n,
            widthstr("map", options.mapping_width, 40),
            len,
            "mapping name",
        ),
        count=(
            "Count",
            lambda n: pt[n]["count"],
            "% 5s",
            sum,
            "number of mappings found",
        ),
        pids=(
            "PIDs count",
            lambda n: pt[n]["pids"],
            "% 5s",
            sum,
            "number of PIDs using mapping",
        ),
        pids_list=(
            "PIDs list",
            lambda n: pt[n]["pids_list"],
            widthstr("pids_list", options.pids_width, 40),
            len,
            "list of pids",
        ),
        swap=(
            "Swap",
            lambda n: pt[n]["swap"],
            "% 8a",
            sum,
            "amount of swap space consumed (ignoring sharing)",
        ),
        uss=(
            "USS",
            lambda n: pt[n]["private_clean"] + pt[n]["private_dirty"],
            "% 8a",
            sum,
            "unique set size",
        ),
        rss=(
            "RSS",
            lambda n: pt[n]["rss"],
            "% 8a",
            sum,
            "resident set size (ignoring sharing)",
        ),
        pss=(
            "PSS",
            lambda n: pt[n]["pss"],
            "% 8a",
            sum,
            "proportional set size (including sharing)",
        ),
        vss=(
            "VSS",
            lambda n: pt[n]["size"],
            "% 8a",
            sum,
            "virtual set size (total virtual address space mapped)",
        ),
        avgpss=(
            "AVGPSS",
            lambda n: int(1.0 * pt[n]["pss"] / pt[n]["pids"]),
            "% 8a",
            sum,
            "average PSS per PID",
        ),
        avguss=(
            "AVGUSS",
            lambda n: int(
                1.0 * (pt[n]["private_clean"] + pt[n]["private_dirty"]) / pt[n]["pids"]
            ),
            "% 8a",
            sum,
            "average USS per PID",
        ),
        avgrss=(
            "AVGRSS",
            lambda n: int(1.0 * pt[n]["rss"] / pt[n]["pids"]),
            "% 8a",
            sum,
            "average RSS per PID",
        ),
    )
    columns = options.columns or "map pids avgpss pss"

    showtable(list(pt.keys()), fields, columns.split(), options.sort or "pss")


def showusers(pidmaps_f=pidmaps) -> None:

    p = proc.pids()
    pt = usertotals(p, proc.allowed_cpu_count(), pidmaps_f=pidmaps_f)
    pss_min, rss_min = _mem_thresholds()
    if pss_min or rss_min:
        pt = {k: v for k, v in pt.items()
              if v['pss'] >= pss_min and v['rss'] >= rss_min}

    def showuser(u):
        if options.numeric:
            return u
        return proc.username(u)

    fields = dict(
        user=(
            "User",
            showuser,
            widthstr("user", options.user_width, 8),
            None,
            "user name or ID",
        ),
        count=("Count", lambda n: pt[n]["count"], "% 5s", sum, "number of processes"),
        swap=(
            "Swap",
            lambda n: pt[n]["swap"],
            "% 8a",
            sum,
            "amount of swapspace consumed (ignoring sharing)",
        ),
        uss=(
            "USS",
            lambda n: pt[n]["private_clean"] + pt[n]["private_dirty"],
            "% 8a",
            sum,
            "unique set size",
        ),
        rss=(
            "RSS",
            lambda n: pt[n]["rss"],
            "% 8a",
            sum,
            "resident set size (ignoring sharing)",
        ),
        pss=(
            "PSS",
            lambda n: pt[n]["pss"],
            "% 8a",
            sum,
            "proportional set size (including sharing)",
        ),
        vss=(
            "VSS",
            lambda n: pt[n]["pss"],
            "% 8a",
            sum,
            "virtual set size (total virtual memory mapped)",
        ),
    )
    columns = options.columns or "user count swap uss pss rss"

    showtable(list(pt.keys()), fields, columns.split(), options.sort or "pss")


def kernelsize() -> int:
    kernelsize = 0
    if not kernelsize and options.kernel:
        try:
            d = os.popen("size %s" % options.kernel).readlines()[1].split()
            if int(d[1]) == 0:  # data part missing, seems like packed file
                # try some heuristic to find gzipped part in kernel image
                packedkernel = open(options.kernel, "rb").read()
                pos = packedkernel.find(b"\x1F\x8B")
                if pos >= 0 and pos < 25000:
                    sys.stderr.write(
                        "Parameter '%s' should be an original uncompressed compiled kernel file.\n"
                        % options.kernel
                    )
                    sys.stderr.write(
                        "Maybe uncompressed kernel can be extracted by the command:\n"
                        "  dd if=%s bs=1 skip=%d | gzip -d >%s.unpacked\n\n"
                        % (options.kernel, pos, options.kernel)
                    )
            else:
                kernelsize = int(int(d[3]) / 1024 + 0.5)
        except:
            pass
    return kernelsize


def showsystem() -> None:
    t = totalmem()
    ki = kernelsize()
    m = MemData()

    mt = m("memtotal")
    f = m("memfree")

    # total amount used by hardware
    fh = max(t - mt - ki, 0)

    # total amount mapped into userspace (ie mapped an unmapped pages)
    u = m("anonpages") + m("mapped")

    # total amount allocated by kernel not for userspace
    kd = mt - f - u

    # total amount in kernel caches
    kdc = m("buffers") + m("sreclaimable") + (m("cached") - m("mapped"))

    l = [
        ("firmware/hardware", fh, 0),
        ("kernel image", ki, 0),
        ("kernel dynamic memory", kd, kdc),
        ("userspace memory", u, m("mapped")),
        ("free memory", f, f),
    ]

    fields = dict(
        order=("Order", lambda n: n, "% 1s", lambda x: "", "hierarchical order"),
        area=("Area", lambda n: l[n][0], "%-24s", lambda x: "", "memory area"),
        used=("Used", lambda n: l[n][1], "%10a", sum, "area in use"),
        cache=(
            "Cache",
            lambda n: l[n][2],
            "%10a",
            sum,
            "area used as reclaimable cache",
        ),
        noncache=(
            "Noncache",
            lambda n: l[n][1] - l[n][2],
            "%10a",
            sum,
            "area not reclaimable",
        ),
    )

    columns = options.columns or "area used cache noncache"
    showtable(list(range(len(l))), fields, columns.split(), options.sort or "order")


def showfields(fields, f) -> None:
    if type(f) in (list, set):
        print("unknown fields: " + " ".join(f))
    else:
        print("unknown field %s" % f)
    print("known fields:")
    for l in sorted(fields):
        print("%-8s %s" % (l, fields[l][-1]))


def autosize(columns: Sized, fields, rows):
    colsizes = {}
    for c in columns:
        if c in ignore_autosize:
            continue
        sizes = [1]

        if not options.no_header:
            sizes.append(len(fields[c][0]))

        if (options.abbreviate or options.percent) and "a" in fields[c][2]:
            sizes.append(7)
        else:
            for r in rows:
                sizes.append(len(str(fields[c][1](r))))

        colsizes[c] = max(sizes)

    overflowcols = (set(["command", "map"]) & set(columns)) - ignore_autosize
    if len(overflowcols) > 0:
        overflowcol = overflowcols.pop()
        totnoflow = sum(colsizes.values()) - colsizes[overflowcol]
        try:
            ttyrows, ttycolumns = os.popen("stty size", "r").read().split()
            ttyrows, ttycolumns = int(ttyrows), int(ttycolumns)
        except:
            ttyrows, ttycolumns = (24, 80)
        maxflowcol = ttycolumns - totnoflow - len(columns)
        maxflowcol = max(maxflowcol, 10)
        colsizes[overflowcol] = min(colsizes[overflowcol], maxflowcol)

    return colsizes


def showdelta(a, total):
    """Format a signed memory delta for display."""
    if a == 0:
        return '0'
    if options.abbreviate:
        return ('+' if a > 0 else '-') + units(abs(a) * 1024)
    elif options.percent:
        return 'N/A' if total == 0 else '%+.2f%%' % (100.0 * a / total)
    return '%+d' % a


def _collect_proc_totals(source):
    global proc, options
    options.source = source
    proc = ProcessData()
    pidmaps_f = pidmaps_rollup if proc.use_smaps_rollup() else pidmaps
    pids = proc.pids()
    totals = processtotals(pids, proc.allowed_cpu_count(), pidmaps_f)
    cmdlines = {pid: proc.pidcmd(pid) for pid in totals}
    return totals, cmdlines


def _collect_map_totals(source, is_aggregate=False):
    global proc, options
    options.source = source
    proc = ProcessData()
    pids = proc.pids()
    return maptotals(pids, proc.allowed_cpu_count(), is_aggregate)


def _collect_system_values(source):
    global proc, options
    options.source = source
    proc = ProcessData()
    m = MemData()
    t = totalmem()
    ki = kernelsize()
    mt = m("memtotal")
    f = m("memfree")
    fh = max(t - mt - ki, 0)
    u = m("anonpages") + m("mapped")
    kd = mt - f - u
    kdc = m("buffers") + m("sreclaimable") + (m("cached") - m("mapped"))
    return [
        ("firmware/hardware", fh, 0),
        ("kernel image", ki, 0),
        ("kernel dynamic memory", kd, kdc),
        ("userspace memory", u, m("mapped")),
        ("free memory", f, f),
    ]


def _series_label(path):
    """Derive a short column header from a tarfile path."""
    name = os.path.basename(path)
    name = re.sub(r'\.(tar\.gz|tar\.bz2|tar\.xz|tar|tgz|tbz2)$', '', name, flags=re.I)
    m = re.search(r'(\d{4}[._-]\d{2}[._-]\d{2}[._T-]\d{2}[._-]\d{2}(?:[._-]\d{2})?)', name)
    if m:
        return m.group(1)
    return name


def _collect_series_snapshot(source):
    """Return ({key: pss_kb}, {key: display_name}) for one capture."""
    if options.chromium:
        totals, cmdlines = _collect_proc_totals(source)
        groups = _group_by_chromium_role(totals, cmdlines)
        return {k: groups[k]['pss'] for k in groups}, {k: groups[k]['label'] for k in groups}
    elif options.mappings or options.aggregates:
        totals = _collect_map_totals(source, options.aggregates)
        return {name: totals[name]['pss'] for name in totals}, {}
    else:
        totals, cmdlines = _collect_proc_totals(source)
        pss = {}
        for pid in totals:
            cmd = cmdlines.get(pid, '?')
            pss[cmd] = pss.get(cmd, 0) + totals[pid]['pss']
        return pss, {}


def showseries():
    def _sort_key(p):
        m = re.search(r'\d+', os.path.basename(p))
        return int(m.group()) if m else float('inf')

    sources = sorted(options.series, key=_sort_key)
    # Use t0/t1/... as collision-safe internal keys; keep display labels separate
    col_keys = ['t%d' % i for i in range(len(sources))]
    raw_headers = [_series_label(src) for src in sources]
    seen_h = {}
    col_headers = []
    for h in raw_headers:
        if h in seen_h:
            seen_h[h] += 1
            col_headers.append('%s_%d' % (h, seen_h[h]))
        else:
            seen_h[h] = 0
            col_headers.append(h)

    snapshots    = []   # list of {key: pss_kb}
    display_names = {}  # role/map key → display name
    for src, col_key in zip(sources, col_keys):
        pss, names = _collect_series_snapshot(src)
        snapshots.append(pss)
        display_names.update(names)

    if not snapshots:
        return

    # Collect all row keys in first-seen order
    all_keys = []
    seen_keys = set()
    for snap in snapshots:
        for k in snap:
            if k not in seen_keys:
                all_keys.append(k)
                seen_keys.add(k)

    pss_min, _ = _mem_thresholds()
    rows = []
    for key in all_keys:
        vals = [snap.get(key, 0) for snap in snapshots]
        if pss_min and max(vals) < pss_min:
            continue
        delta = vals[-1] - vals[0] if len(vals) > 1 else 0
        row = {'key': key, 'name': display_names.get(key, key), 'delta_pss': delta}
        for ck, v in zip(col_keys, vals):
            row[ck] = v
        rows.append(row)

    sort_key = options.sort or 'delta_pss'
    if sort_key == 'delta_pss':
        rows.sort(key=lambda r: abs(r['delta_pss']), reverse=not options.reverse)
    else:
        rows.sort(key=lambda r: r.get(sort_key, 0), reverse=bool(options.reverse))

    if options.output == 'json':
        out = []
        for r in rows:
            entry = {'name': r['name']}
            for ck, ch in zip(col_keys, col_headers):
                entry[ch] = r[ck]
            entry['delta_pss'] = r['delta_pss']
            out.append(entry)
        print(json.dumps(out, indent=2))
        return

    if options.output == 'csv':
        writer = csv.writer(sys.stdout)
        if not options.no_header:
            writer.writerow(['name'] + col_headers + ['delta_pss'])
        for r in rows:
            writer.writerow([r['name']] + [r[ck] for ck in col_keys] + [r['delta_pss']])
        return

    # Text table
    mt = totalmem()

    if options.output == 'html':
        all_col_hdrs = (['Role' if options.chromium else ('Map' if (options.mappings or options.aggregates) else 'Command')]
                        + col_headers + ['\u0394PSS'])
        display_rows, raw_rows = [], []
        for r in rows:
            d_row = [r['name']]
            rv_row = [r['name']]
            for ck in col_keys:
                d_row.append(str(showamount(r[ck], mt)))
                rv_row.append(r[ck])
            d_row.append(showdelta(r['delta_pss'], mt))
            rv_row.append(r['delta_pss'])
            display_rows.append(d_row)
            raw_rows.append(rv_row)
        # Bar on last time column (index = len(col_keys), 0-indexed after name col)
        bar_col = len(col_keys) if col_keys else None
        _emit_html('smem series', all_col_hdrs, display_rows, raw_rows, bar_col)
        return

    if options.chromium:
        name_hdr = 'Role'
        name_default = options.role_width if options.role_width > 0 else 44
    elif options.mappings or options.aggregates:
        name_hdr = 'Map'
        name_default = options.mapping_width if options.mapping_width > 0 else 40
    else:
        name_hdr = 'Command'
        name_default = options.cmd_width if options.cmd_width > 0 else 27

    if options.autosize:
        name_w = max([len(r['name']) for r in rows] + [len(name_hdr)], default=name_default)
        other_w = len(col_keys) * 9 + 10  # 8 chars per value col + 9 for delta + separators
        try:
            _, tty_w = os.popen("stty size", "r").read().split()
            tty_w = int(tty_w)
        except Exception:
            tty_w = 80
        name_w = min(name_w, max(10, tty_w - other_w))
    else:
        name_w = name_default

    name_fmt = '%%-%d.%ds' % (name_w, name_w)

    if not options.no_header:
        parts = [name_fmt % name_hdr]
        for ch in col_headers:
            parts.append('%8.8s' % ch)
        parts.append('%9.9s' % 'DPSS')
        print(' '.join(parts))

    for r in rows:
        parts = [name_fmt % r['name']]
        for ck in col_keys:
            parts.append('%8s' % showamount(r[ck], mt))
        parts.append('%9s' % showdelta(r['delta_pss'], mt))
        print(' '.join(parts))


def showdiff():
    source_a, source_b = options.diff

    if options.mappings or options.aggregates:
        data_a = _collect_map_totals(source_a, options.aggregates)
        data_b = _collect_map_totals(source_b, options.aggregates)
        all_keys = set(data_a) | set(data_b)
        rows = []
        for name in all_keys:
            a = data_a.get(name, {})
            b = data_b.get(name, {})
            uss_a = a.get('private_clean', 0) + a.get('private_dirty', 0)
            uss_b = b.get('private_clean', 0) + b.get('private_dirty', 0)
            status = ' ' if name in data_a and name in data_b else ('+' if name in data_b else '-')
            rows.append(dict(
                status=status, map=name,
                pss_a=a.get('pss', 0), pss_b=b.get('pss', 0),
                delta_pss=b.get('pss', 0) - a.get('pss', 0),
                uss_a=uss_a, uss_b=uss_b, delta_uss=uss_b - uss_a,
                rss_a=a.get('rss', 0), rss_b=b.get('rss', 0),
                delta_rss=b.get('rss', 0) - a.get('rss', 0),
                swap_a=a.get('swap', 0), swap_b=b.get('swap', 0),
                delta_swap=b.get('swap', 0) - a.get('swap', 0),
            ))
        default_columns = 'status map pss_a pss_b delta_pss'

    elif options.system:
        sys_a = {area: (used, cache) for area, used, cache in _collect_system_values(source_a)}
        sys_b = {area: (used, cache) for area, used, cache in _collect_system_values(source_b)}
        order = [area for area, _, _ in _collect_system_values(source_a)]
        rows = []
        for area in order:
            a_used, a_cache = sys_a[area]
            b_used, b_cache = sys_b.get(area, (0, 0))
            rows.append(dict(
                area=area,
                used_a=a_used, used_b=b_used, delta_used=b_used - a_used,
                cache_a=a_cache, cache_b=b_cache, delta_cache=b_cache - a_cache,
                noncache_a=a_used - a_cache, noncache_b=b_used - b_cache,
                delta_noncache=(b_used - b_cache) - (a_used - a_cache),
            ))
        default_columns = 'area used_a used_b delta_used'

    elif options.chromium:
        data_a, cmdlines_a = _collect_proc_totals(source_a)
        data_b, cmdlines_b = _collect_proc_totals(source_b)
        groups_a = _group_by_chromium_role(data_a, cmdlines_a)
        groups_b = _group_by_chromium_role(data_b, cmdlines_b)
        rows = []
        for key in set(groups_a) | set(groups_b):
            a = groups_a.get(key, {})
            b = groups_b.get(key, {})
            status = ' ' if key in groups_a and key in groups_b else ('+' if key in groups_b else '-')
            rows.append(dict(
                status=status,
                role=b.get('label') or a.get('label', key),
                count_a=a.get('count', 0), count_b=b.get('count', 0),
                pss_a=a.get('pss', 0), pss_b=b.get('pss', 0),
                delta_pss=b.get('pss', 0) - a.get('pss', 0),
                uss_a=a.get('uss', 0), uss_b=b.get('uss', 0),
                delta_uss=b.get('uss', 0) - a.get('uss', 0),
                rss_a=a.get('rss', 0), rss_b=b.get('rss', 0),
                delta_rss=b.get('rss', 0) - a.get('rss', 0),
                swap_a=a.get('swap', 0), swap_b=b.get('swap', 0),
                delta_swap=b.get('swap', 0) - a.get('swap', 0),
            ))
        default_columns = 'status role count_a count_b pss_a pss_b delta_pss'

    else:
        data_a, cmdlines_a = _collect_proc_totals(source_a)
        data_b, cmdlines_b = _collect_proc_totals(source_b)
        rows = []
        for pid in set(data_a) | set(data_b):
            cmd_a = cmdlines_a.get(pid, '')
            cmd_b = cmdlines_b.get(pid, '')
            in_a, in_b = pid in data_a, pid in data_b
            if in_a and in_b and cmd_a != cmd_b:
                # PID reused by a different process between captures
                a = data_a[pid]
                rows.append(dict(status='-', pid=pid, command=cmd_a,
                                 pss_a=a['pss'], pss_b=0, delta_pss=-a['pss'],
                                 uss_a=a['uss'], uss_b=0, delta_uss=-a['uss'],
                                 rss_a=a['rss'], rss_b=0, delta_rss=-a['rss'],
                                 swap_a=a['swap'], swap_b=0, delta_swap=-a['swap']))
                b = data_b[pid]
                rows.append(dict(status='+', pid=pid, command=cmd_b,
                                 pss_a=0, pss_b=b['pss'], delta_pss=b['pss'],
                                 uss_a=0, uss_b=b['uss'], delta_uss=b['uss'],
                                 rss_a=0, rss_b=b['rss'], delta_rss=b['rss'],
                                 swap_a=0, swap_b=b['swap'], delta_swap=b['swap']))
                continue
            a = data_a.get(pid, {})
            b = data_b.get(pid, {})
            status = ' ' if in_a and in_b else ('+' if in_b else '-')
            rows.append(dict(
                status=status, pid=pid, command=cmd_b if in_b else cmd_a,
                pss_a=a.get('pss', 0), pss_b=b.get('pss', 0),
                delta_pss=b.get('pss', 0) - a.get('pss', 0),
                uss_a=a.get('uss', 0), uss_b=b.get('uss', 0),
                delta_uss=b.get('uss', 0) - a.get('uss', 0),
                rss_a=a.get('rss', 0), rss_b=b.get('rss', 0),
                delta_rss=b.get('rss', 0) - a.get('rss', 0),
                swap_a=a.get('swap', 0), swap_b=b.get('swap', 0),
                delta_swap=b.get('swap', 0) - a.get('swap', 0),
            ))
        default_columns = 'status pid command pss_a pss_b delta_pss'

    pss_min, rss_min = _mem_thresholds()
    if (pss_min or rss_min) and not options.system:
        rows = [r for r in rows
                if max(r.get('pss_a', 0), r.get('pss_b', 0)) >= pss_min
                and max(r.get('rss_a', 0), r.get('rss_b', 0)) >= rss_min]

    sort_key = options.sort or 'delta_pss' if not options.system else 'area'
    if sort_key in ('delta_pss', 'delta_uss', 'delta_rss', 'delta_swap',
                    'delta_used', 'delta_cache', 'delta_noncache'):
        rows.sort(key=lambda r: abs(r[sort_key]), reverse=not options.reverse)
    else:
        rows.sort(key=lambda r: r.get(sort_key, 0), reverse=bool(options.reverse))

    columns = (options.columns or default_columns).split()

    mt = totalmem()
    st = MemData()("swaptotal")

    MEM_COLS  = {'pss_a', 'pss_b', 'uss_a', 'uss_b', 'rss_a', 'rss_b',
                 'used_a', 'used_b', 'cache_a', 'cache_b', 'noncache_a', 'noncache_b'}
    SWAP_COLS = {'swap_a', 'swap_b'}
    DELTA_MEM = {'delta_pss', 'delta_uss', 'delta_rss',
                 'delta_used', 'delta_cache', 'delta_noncache'}
    DELTA_SWP = {'delta_swap'}

    HEADERS = {
        'status': '', 'pid': 'PID', 'command': 'Command', 'map': 'Map', 'area': 'Area',
        'role': 'Role', 'count_a': 'CNT_A', 'count_b': 'CNT_B',
        'pss_a': 'PSS_A', 'pss_b': 'PSS_B', 'delta_pss': '\u0394PSS',
        'uss_a': 'USS_A', 'uss_b': 'USS_B', 'delta_uss': '\u0394USS',
        'rss_a': 'RSS_A', 'rss_b': 'RSS_B', 'delta_rss': '\u0394RSS',
        'swap_a': 'SWAP_A', 'swap_b': 'SWAP_B', 'delta_swap': '\u0394SWAP',
        'used_a': 'USED_A', 'used_b': 'USED_B', 'delta_used': '\u0394USED',
        'cache_a': 'CACHE_A', 'cache_b': 'CACHE_B', 'delta_cache': '\u0394CACHE',
        'noncache_a': 'NCACHE_A', 'noncache_b': 'NCACHE_B', 'delta_noncache': '\u0394NCACHE',
    }

    if options.output == 'json':
        print(json.dumps(rows, indent=2))
        return

    if options.output == 'csv':
        writer = csv.writer(sys.stdout)
        if not options.no_header:
            writer.writerow(columns)
        for row in rows:
            writer.writerow([row[c] for c in columns])
        return

    if options.output == 'html':
        col_hdrs = [HEADERS.get(c, c) for c in columns]
        display_rows, raw_rows = [], []
        for row in rows:
            d_row, r_row = [], []
            for c in columns:
                v = row[c]
                r_row.append(v)
                if c in MEM_COLS:
                    d_row.append(str(showamount(v, mt)))
                elif c in SWAP_COLS:
                    d_row.append(str(showamount(v, st)))
                elif c in DELTA_MEM:
                    d_row.append(showdelta(v, mt))
                elif c in DELTA_SWP:
                    d_row.append(showdelta(v, st))
                else:
                    d_row.append(str(v))
            display_rows.append(d_row)
            raw_rows.append(r_row)
        bar_col = next((i for i, c in enumerate(columns) if c == 'pss_b'), None)
        _emit_html('smem diff', col_hdrs, display_rows, raw_rows, bar_col)
        return

    # Table output

    cmd_w  = options.cmd_width     if options.cmd_width     > 0 else 27
    map_w  = options.mapping_width if options.mapping_width > 0 else 40
    role_w = options.role_width    if options.role_width    > 0 else 44

    # Autosize variable-width text columns
    TEXT_OVERFLOW = ('command', 'map', 'role')
    FIXED_W = {'status': 1, 'pid': 6, 'count_a': 5, 'count_b': 5, 'area': 24}
    text_w = {}
    for c in columns:
        if c not in TEXT_OVERFLOW:
            continue
        default = cmd_w if c == 'command' else (role_w if c == 'role' else map_w)
        if options.autosize:
            sizes = [len(HEADERS.get(c, c))]
            for row in rows:
                sizes.append(len(str(row.get(c, ''))))
            text_w[c] = max(sizes)
        else:
            text_w[c] = default
    if options.autosize:
        overflow_cols = [c for c in columns if c in TEXT_OVERFLOW]
        if overflow_cols:
            oc = overflow_cols[0]
            other_w = sum(
                FIXED_W.get(c, 9 if c in DELTA_MEM | DELTA_SWP else 8)
                for c in columns if c != oc and c not in TEXT_OVERFLOW
            ) + sum(text_w[c] for c in columns if c in TEXT_OVERFLOW and c != oc)
            other_w += len(columns) - 1
            try:
                _, tty_w = os.popen("stty size", "r").read().split()
                tty_w = int(tty_w)
            except Exception:
                tty_w = 80
            text_w[oc] = min(text_w[oc], max(10, tty_w - other_w))

    col_fmt = []
    col_fn  = []
    for c in columns:
        if c == 'status':
            col_fmt.append('%-1s');  col_fn.append(lambda v: v)
        elif c == 'pid':
            col_fmt.append('%6s');   col_fn.append(lambda v: v)
        elif c == 'command':
            w = text_w.get(c, cmd_w)
            col_fmt.append('%%-%d.%ds' % (w, w))
            col_fn.append(lambda v: v)
        elif c == 'map':
            w = text_w.get(c, map_w)
            col_fmt.append('%%-%d.%ds' % (w, w))
            col_fn.append(lambda v: v)
        elif c == 'area':
            col_fmt.append('%-24s');  col_fn.append(lambda v: v)
        elif c == 'role':
            w = text_w.get(c, role_w)
            col_fmt.append('%%-%d.%ds' % (w, w))
            col_fn.append(lambda v: v)
        elif c in ('count_a', 'count_b'):
            col_fmt.append('%5s');    col_fn.append(lambda v: v)
        elif c in MEM_COLS:
            col_fmt.append('%8s')
            col_fn.append(lambda v, t=mt: showamount(v, t))
        elif c in SWAP_COLS:
            col_fmt.append('%8s')
            col_fn.append(lambda v, t=st: showamount(v, t))
        elif c in DELTA_MEM:
            col_fmt.append('%9s')
            col_fn.append(lambda v, t=mt: showdelta(v, t))
        elif c in DELTA_SWP:
            col_fmt.append('%9s')
            col_fn.append(lambda v, t=st: showdelta(v, t))
        else:
            col_fmt.append('%8s');   col_fn.append(lambda v: v)

    fmt = ' '.join(col_fmt)
    if not options.no_header:
        print(fmt % tuple(HEADERS.get(c, c) for c in columns))
    for row in rows:
        print(fmt % tuple(fn(row[c]) for fn, c in zip(col_fn, columns)))


_HTML_CSS = """\
body{font-family:monospace;font-size:13px;margin:16px}
h1{font-size:14px;font-weight:bold;margin-bottom:8px}
table{border-collapse:collapse;width:max-content}
th,td{padding:3px 10px;text-align:right;border-bottom:1px solid #ddd;white-space:nowrap}
th:first-child,td:first-child{text-align:left}
th{background:#f0f0f0;cursor:pointer;user-select:none}
th:hover{background:#e0e0e0}
th.asc::after{content:" \u25b2";font-size:10px}
th.desc::after{content:" \u25bc";font-size:10px}
tr:hover td{background:rgba(0,0,0,0.03)}
.bar-cell{position:relative;min-width:60px}
.bar-bg{position:absolute;left:0;top:1px;bottom:1px;background:rgba(70,130,180,0.22);z-index:0;border-radius:2px}
.bar-val{position:relative;z-index:1}
"""

_HTML_JS = """\
(function(){
var ths=document.querySelectorAll('th'),sortCol=-1,sortAsc=true;
ths.forEach(function(th,i){
  th.addEventListener('click',function(){
    var tbody=th.closest('table').querySelector('tbody');
    var rows=Array.from(tbody.querySelectorAll('tr'));
    var asc=(sortCol===i)?!sortAsc:true;
    sortCol=i;sortAsc=asc;
    ths.forEach(function(t){t.className='';});
    th.className=asc?'asc':'desc';
    rows.sort(function(a,b){
      var av=a.querySelectorAll('td')[i].dataset.val||'';
      var bv=b.querySelectorAll('td')[i].dataset.val||'';
      var an=parseFloat(av),bn=parseFloat(bv);
      if(!isNaN(an)&&!isNaN(bn))return asc?an-bn:bn-an;
      return asc?av.localeCompare(bv):bv.localeCompare(av);
    });
    rows.forEach(function(r){tbody.appendChild(r);});
  });
});
})();
"""


def _html_escape(s):
    return str(s).replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')


def _emit_html(title, col_headers, display_rows, raw_rows, bar_col=None):
    """Emit a self-contained sortable HTML table to stdout."""
    bar_max = None
    if bar_col is not None and raw_rows:
        try:
            bar_max = max(float(r[bar_col]) for r in raw_rows
                         if r[bar_col] not in ('', None))
        except (ValueError, TypeError):
            bar_max = None
        if not bar_max or bar_max <= 0:
            bar_col = None

    lines = [
        '<!DOCTYPE html><html><head><meta charset="utf-8">',
        '<title>%s</title>' % _html_escape(title),
        '<style>%s</style></head><body>' % _HTML_CSS,
        '<h1>%s</h1><table><thead><tr>' % _html_escape(title),
    ]
    for h in col_headers:
        lines.append('<th>%s</th>' % _html_escape(h))
    lines.append('</tr></thead><tbody>')
    for d_row, r_row in zip(display_rows, raw_rows):
        lines.append('<tr>')
        for j, (d, r) in enumerate(zip(d_row, r_row)):
            dv = _html_escape(d)
            rv = _html_escape(str(r))
            if bar_col is not None and j == bar_col:
                try:
                    pct = min(100.0, 100.0 * float(r) / bar_max)
                except (ValueError, TypeError):
                    pct = 0.0
                lines.append('<td class="bar-cell" data-val="%s">'
                             '<div class="bar-bg" style="width:%.1f%%"></div>'
                             '<span class="bar-val">%s</span></td>' % (rv, pct, dv))
            else:
                lines.append('<td data-val="%s">%s</td>' % (rv, dv))
        lines.append('</tr>')
    lines.append('</tbody></table><script>%s</script></body></html>' % _HTML_JS)
    print('\n'.join(lines))


def showtable(rows, fields, columns, sort) -> None:
    if sort not in fields:
        showfields(fields, sort)
        sys.exit(-1)

    missing = set(columns) - set(fields)
    if len(missing) > 0:
        showfields(fields, missing)
        sys.exit(-1)

    sorted_rows = sorted(rows, key=lambda n: fields[sort][1](n), reverse=bool(options.reverse))

    if options.output == 'json':
        data = [{c: fields[c][1](n) for c in columns} for n in sorted_rows]
        print(json.dumps(data, indent=2))
        return

    if options.output == 'csv':
        writer = csv.writer(sys.stdout)
        if not options.no_header:
            writer.writerow(columns)
        for n in sorted_rows:
            writer.writerow([fields[c][1](n) for c in columns])
        return

    mt = totalmem()
    memdata = MemData()
    st = memdata("swaptotal")

    if options.output == 'html':
        col_hdrs = [fields[c][0] for c in columns]
        display_rows, raw_rows = [], []
        for n in sorted_rows:
            d_row, r_row = [], []
            for c in columns:
                raw = fields[c][1](n)
                r_row.append(raw)
                fmt = fields[c][2]
                if 'a' in fmt:
                    total = st if c == 'swap' else mt
                    d_row.append(str(showamount(raw, total)))
                else:
                    d_row.append(str(raw))
            display_rows.append(d_row)
            raw_rows.append(r_row)
        bar_col = next((i for i, c in enumerate(columns) if c in ('pss', 'used')), None)
        _emit_html('smem', col_hdrs, display_rows, raw_rows, bar_col)
        return

    header = ""
    table_format = ""
    formatter = []

    if options.autosize:
        colsizes = autosize(columns, fields, rows)
    else:
        colsizes = {}

    for n in columns:
        f = fields[n][2]
        if "a" in f:
            if n == "swap":
                formatter.append(lambda x: showamount(x, st))
            else:
                formatter.append(lambda x: showamount(x, mt))
            f = f.replace("a", "s")
        else:
            formatter.append(lambda x: x)
        if n in colsizes:
            f = re.sub(r"[0-9]+", str(colsizes[n]), f)
        table_format += f + " "
        header += f % fields[n][0] + " "

    if not options.no_header:
        print(header)

    for n in sorted_rows:
        r = [fields[c][1](n) for c in columns]
        print(table_format % tuple([f(v) for f, v in zip(formatter, r)]))

    if options.totals:
        t = []
        for c in columns:
            f = fields[c][3]
            if f:
                t.append(f([fields[c][1](n) for n in rows]))
            else:
                t.append("")

        print("-" * len(header))
        print(table_format % tuple([f(v) for f, v in zip(formatter, t)]))


def parse_arguments(argv=None) -> argparse.Namespace:

    argparser = argparse.ArgumentParser(
        prog="smem",
        description="""
                    smem is a tool that can give numerous reports on memory usage on Linux systems.
                    Unlike existing tools, smem can report proportional set size (PSS), which is a
                    more meaningful representation of the amount of memory used by libraries and
                    applications in a virtual memory system.
                    """,
        epilog="""
               For more information please visit:
               https://github.com/kwkroeger/smem
               """,
    )

    argparser.add_argument(
        "-H", "--no-header", action="store_true", help="Disable header line"
    )

    argparser.add_argument(
        "-c", "--columns", default=None, type=str, help="Columns to show"
    )

    argparser.add_argument(
        "-a",
        "--autosize",
        action="store_true",
        help="Size columns to fit terminal size",
    )

    argparser.add_argument(
        "-R", "--realmem", default=None, type=str, help="Amount of physical RAM"
    )

    argparser.add_argument(
        "-K", "--kernel", default=None, type=str, help="Path to kernel image"
    )

    filter_group = argparser.add_argument_group("Filter")
    filter_group.add_argument(
        "-P", "--processfilter", default=None, type=str, help="Process filter regex"
    )

    filter_group.add_argument(
        "-M", "--mapfilter", default=None, type=str, help="Process map regex"
    )

    filter_group.add_argument(
        "-U", "--userfilter", default=None, type=str, help="Process users regex"
    )

    filter_group.add_argument(
        "--min-pss", default=None, type=str,
        help="Exclude entries with PSS below threshold (e.g. 1M, 500K)",
    )

    filter_group.add_argument(
        "--min-rss", default=None, type=str,
        help="Exclude entries with RSS below threshold (e.g. 1M, 500K)",
    )

    show_group = argparser.add_argument_group("Show")
    show_group.add_argument(
        "-A", "--aggregates", action="store_true", help="Show mapping aggregates"
    )

    show_group.add_argument(
        "-C", "--chromium", action="store_true",
        help="Show Chromium process roles (browser, renderer, gpu-process, etc.)",
    )

    show_group.add_argument(
        "-m", "--mappings", action="store_true", help="Show mappings"
    )

    show_group.add_argument("-u", "--users", action="store_true", help="Show users")

    show_group.add_argument(
        "-w", "--system", action="store_true", help="Show whole system"
    )

    show_group.add_argument(
        "-p", "--percent", action="store_true", help="Show percentage"
    )

    show_group.add_argument(
        "-k", "--abbreviate", action="store_true", help="Show unit suffixes"
    )

    show_group.add_argument("-t", "--totals", action="store_true", help="Show totals")

    show_group.add_argument(
        "-o", "--output",
        default="table",
        choices=["table", "json", "csv", "html"],
        help="Output format (default: table)",
    )

    sort_group = argparser.add_argument_group("Sort")
    sort_group.add_argument("-n", "--numeric", action="store_true", help="Numeric sort")

    sort_group.add_argument(
        "-s", "--sort", default=None, type=str, help="Field to sort on"
    )

    sort_group.add_argument("-r", "--reverse", action="store_true", help="Reverse sort")

    width_group = argparser.add_argument_group("Width")
    width_group.add_argument(
        "--cmd-width",
        default=-1,
        type=int,
        help="Text width for commands (0=as needed)",
    )

    width_group.add_argument(
        "--name-width",
        default=-1,
        type=int,
        help="Text width for command names (0=as needed)",
    )

    width_group.add_argument(
        "--user-width",
        default=-1,
        type=int,
        help="Text width for user names (0=as needed)",
    )

    width_group.add_argument(
        "--mapping-width",
        default=-1,
        type=int,
        help="Text width for mapping names (0=as needed)",
    )

    width_group.add_argument(
        "--role-width",
        default=-1,
        type=int,
        help="Text width for Chromium role names (0=as needed)",
    )

    width_group.add_argument(
        "--pids-width",
        default=-1,
        type=int,
        help="Text width for PIDS list names (0=as needed)",
    )

    argparser.add_argument(
        "-S", "--source", default=None, type=str, help="/proc data source"
    )

    argparser.add_argument(
        "--diff", nargs=2, metavar=("OLD", "NEW"),
        help="Compare two captures (tarfiles)",
    )

    argparser.add_argument(
        "--series", nargs='+', metavar="TAR",
        help="Show PSS time-series across multiple captures (tarfiles)",
    )

    argparser.add_argument(
        "--pid",
        default=None,
        type=int,
        help="Show just process memory based on one pid",
    )

    return argparser.parse_args()


def main() -> None:
    """Main function for smem"""

    # TODO Remove the necessity of globals, this is a temporary workaround until functions have been updated
    global ignore_autosize
    global options
    global proc

    options = parse_arguments(sys.argv)
    ignore_autosize = set()

    # Check if Linux kernel supports smaps_rollup

    proc = ProcessData()
    pidmaps_f = pidmaps_rollup if proc.use_smaps_rollup() else pidmaps

    try:
        if options.series:
            showseries()
        elif options.diff:
            showdiff()
        elif options.chromium:
            showchromium(pidmaps_f)
        elif options.mappings:
            showmaps()
        elif options.aggregates:
            showmaps(True)
        elif options.users:
            showusers(pidmaps_f)
        elif options.system:
            showsystem()
        else:
            showpids(pidmaps_f)
    except IOError as e:
        if e.errno == errno.EPIPE:
            pass
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
